# hello-chtc.sub
# My very first HTCondor submit file
s1=1272
# start scan at this SNP index value
# locus1: 1292; locus2: 1401. Add +/-20 to get full scan range
nsnp=150 
# length of scan in number of SNPs
# which run in the experimental design?
run_num=310
#
# Specify the HTCondor Universe (vanilla is the default and is used
#  for almost all jobs), the desired name of the HTCondor log file,
#  and the desired name of the standard error file.  
#  Wherever you see $(Cluster), HTCondor will insert the queue number
#  assigned to this set of jobs at the time of submission.
universe = vanilla
log = pvl-$(Process)-run$(run_num).log
error = pvl-$(Process)-run$(run_num).err
#
# Specify your executable (single binary or a script that runs several
#  commands), arguments, and a files for HTCondor to store standard
#  output (or "screen output").
#  $(Process) will be a integer number for each job, starting with "0"
#  and increasing for the relevant number of jobs.
executable = ../shell_scripts/pvl400.sh
arguments = $(Process) $(nsnp) $(s1) $(run_num)
output = pvl-$(Process)-run$(run_num).out
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs. The last of these lines *would* be
#  used if there were any other files needed for the executable to run.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../sim_data/run$(run_num)-400sims,../data,../Rscript,../shell_scripts,http://proxy.chtc.wisc.edu/SQUID/fjboehm/R.tar.gz,http://proxy.chtc.wisc.edu/SQUID/fjboehm/probs_17.RData,http://proxy.chtc.wisc.edu/SQUID/SLIBS.tar.gz
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
request_cpus = 1
request_memory = 1.5GB
request_disk = 1.1GB
#
# extra stuff for 'materialize'
requirements = (OpSysMajorVer == 6) || (OpSysMajorVer == 7)

# which computer grids to use:
+WantFlocking = true
+WantGlideIn = true

# Tell HTCondor to run instances of our job:
queue 400

